/**
 * JSON Schema (YAML) → Zod + inferred types for generated/typescript/src/generated/.
 *
 * Resolves $ref across YAML files before handing to json-schema-to-zod,
 * so primitives are inlined from their canonical source (single source of truth).
 *
 * Processes:
 * - docs/interfaces/schemas/*.data.yaml → event data Zod schemas
 * - docs/interfaces/schemas/primitives/*.yaml → primitive Zod schemas
 * - docs/interfaces/schemas/envelope.yaml → CloudEvents envelope Zod schema
 */
import { mkdir, readdir, writeFile } from 'node:fs/promises';
import { basename, dirname, join } from 'node:path';
import { fileURLToPath } from 'node:url';
import $RefParser from '@apidevtools/json-schema-ref-parser';
import { jsonSchemaToZod } from 'json-schema-to-zod';

const SCRIPT_DIR = dirname(fileURLToPath(import.meta.url));
const REPO_ROOT = join(SCRIPT_DIR, '..');
const SCHEMAS_DIR = join(REPO_ROOT, 'docs/interfaces/schemas');
const PRIMITIVES_DIR = join(SCHEMAS_DIR, 'primitives');
const OUT_DIR = join(REPO_ROOT, 'generated/typescript/src/generated');

const toKebab = (filename: string): string => basename(filename, '.yaml');

const toCamelCase = (kebab: string): string =>
  kebab.replace(/-([a-z])/g, (_, c: string) => c.toUpperCase());

const toPascalCase = (kebab: string): string => {
  const camel = toCamelCase(kebab);
  return camel.charAt(0).toUpperCase() + camel.slice(1);
};

const generateFromSchema = async (
  schemaPath: string,
  outFile: string,
  schemaName: string,
  typeName: string,
): Promise<void> => {
  // Resolve all $ref pointers into a single dereferenced schema
  const dereferenced = await $RefParser.dereference(schemaPath);
  // Cast needed: $RefParser returns JSONSchema but json-schema-to-zod expects Record<string, unknown>
  const schema: Record<string, unknown> = dereferenced as Record<string, unknown>;

  // Remove $schema and $id — json-schema-to-zod doesn't need them and they can confuse it
  delete schema['$schema'];
  delete schema['$id'];

  const body = jsonSchemaToZod(schema, {
    module: 'esm',
    name: schemaName,
    type: typeName,
    zodVersion: 4,
  });

  const file = `/* eslint-disable */
/* Auto-generated by scripts/generate-typescript.ts — do not edit. */
${body}
`;
  await writeFile(outFile, file, 'utf-8');
  console.info('[generate:typescript] wrote', outFile);
};

const run = async (): Promise<void> => {
  await mkdir(OUT_DIR, { recursive: true });

  // 1. Envelope schema
  await generateFromSchema(
    join(SCHEMAS_DIR, 'envelope.yaml'),
    join(OUT_DIR, 'envelope.zod.ts'),
    'envelopeSchema',
    'Envelope',
  );

  // 2. Event data schemas (*.data.yaml)
  const schemaFiles = await readdir(SCHEMAS_DIR);
  const dataFiles = schemaFiles.filter((f) => f.endsWith('.data.yaml'));

  for (const file of dataFiles) {
    const kebab = toKebab(file); // e.g. "order-created.data"
    const baseName = kebab.replace('.data', ''); // e.g. "order-created"
    const camel = toCamelCase(baseName); // e.g. "orderCreated"
    const pascal = toPascalCase(baseName); // e.g. "OrderCreated"

    await generateFromSchema(
      join(SCHEMAS_DIR, file),
      join(OUT_DIR, `${baseName}.data.zod.ts`),
      `${camel}DataSchema`,
      `${pascal}Data`,
    );
  }

  // 3. Primitive schemas
  const primitiveFiles = await readdir(PRIMITIVES_DIR);
  const yamlPrimitives = primitiveFiles.filter((f) => f.endsWith('.yaml'));

  for (const file of yamlPrimitives) {
    const kebab = toKebab(file); // e.g. "order-id"
    const camel = toCamelCase(kebab); // e.g. "orderId"
    const pascal = toPascalCase(kebab); // e.g. "OrderId"

    await generateFromSchema(
      join(PRIMITIVES_DIR, file),
      join(OUT_DIR, `${kebab}.zod.ts`),
      `${camel}Schema`,
      pascal,
    );
  }

  console.info('[generate:typescript] done');
};

run().catch((err: unknown) => {
  console.error(err);
  process.exit(1);
});
