/**
 * JSON Schema (YAML) → Zod + inferred types for generated/typescript/src/generated (gitignored).
 */
import { mkdir, readFile, writeFile } from 'node:fs/promises';
import { dirname, join } from 'node:path';
import { fileURLToPath } from 'node:url';

import { jsonSchemaToZod } from 'json-schema-to-zod';
import { parse as parseYaml } from 'yaml';

const SCRIPT_DIR = dirname(fileURLToPath(import.meta.url));
const REPO_ROOT = join(SCRIPT_DIR, '..');
const SCHEMA_FILE = join(
  REPO_ROOT,
  'docs/interfaces/schemas/order-created.data.yaml',
);
const OUT_FILE = join(
  REPO_ROOT,
  'generated/typescript/src/generated/order-created.data.zod.ts',
);

const run = async (): Promise<void> => {
  const raw = await readFile(SCHEMA_FILE, 'utf-8');
  const schema = parseYaml(raw) as Record<string, unknown>;
  if (typeof schema !== 'object' || schema === null) {
    throw new Error('Schema must parse to an object');
  }

  const body = jsonSchemaToZod(schema, {
    module: 'esm',
    name: 'orderCreatedDataSchema',
    type: 'OrderCreatedData',
    zodVersion: 4,
  });

  const file = `/* eslint-disable */
/* Auto-generated by scripts/generate-typescript.ts — do not edit. */
${body}
`;
  await mkdir(dirname(OUT_FILE), { recursive: true });
  await writeFile(OUT_FILE, file, 'utf-8');
  console.info('[generate:typescript] wrote', OUT_FILE);
};

run().catch((err: unknown) => {
  console.error(err);
  process.exit(1);
});
